setup_repository:
  stage: .pre
  rules:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    # Clone the project from GitLab
    - git clone $Env:CI_PROJECT_URL

  artifacts:
    paths:
      - $Env:CI_PROJECT_DIR
    expire_in: 1 hour


init:
  stage: build
  dependencies:
  - setup_repository
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
  script:
    # Open project
    - matlab -batch "openProject('$Env:CI_PROJECT_DIR')"